name: Custom Deploy

on :
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
        default: 'Testing'
      version:
        description: 'Version (eg: v1)'
        required: true
env:
 node-version: 14.x
jobs:
  env_deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
      url: https://bylumuiportalpltna.azureedge.net/lsf-store-replenishment/
    steps:
      - name: Cancel previous runs
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "!startsWith(github.ref, 'refs/tags/')"

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ github.event.inputs.version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ github.event.inputs.version}}

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          changelog_file: CHANGELOG.md

      - name: Bump version in package.json
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add CHANGELOG.md package.json
          git commit --message "Prepare release ${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
          git tag -a ${{ github.event.inputs.version }} -m "Tagging a new version: ${{ github.event.inputs.version }}"
          git push && git push --tags

      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          name: "Release: ${{ github.event.inputs.version }}"
          draft: false
          prerelease: false
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          card-layout-exit: 'cozy'
          environment: ${{ github.event.inputs.environment }}
          enable-review-diffs: false
          webhook-uri: "https://jda365.webhook.office.com/webhookb2/6366d704-047d-47bf-89bb-9b4849f802f5@2ac36cee-0617-4ac0-bebf-e1ce5dfab86c/IncomingWebhook/29c11d9edf884f75af71f92301e6d8d6/336f29b9-14a6-4ca1-977b-9c7e4881a6ad"