name: Custom Deploy

on :
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
        default: 'Testing'
      version:
        description: 'Version (eg: v1)'
        required: true
env:
 node-version: 14.x
jobs:
  env_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "!startsWith(github.ref, 'refs/tags/')"

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          changelog_file: CHANGELOG.md
          release_notes_file: RELEASE_NOTES.md