name: Custom Deploy

on :
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
        default: 'Testing'
      version:
        description: 'Version (eg: v1)'
        required: true
env:
 node-version: 14.x
jobs:
  env_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "!startsWith(github.ref, 'refs/tags/')"

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Read changelog
        id: changelogBefore
        uses: juliangruber/read-file-action@v1
        with:
          path: CHANGELOG.md

      - name: Echo changelog
        run: echo "${{ steps.changelogBefore.outputs.content }}"

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ github.event.inputs.version}}

      - name: Read changelog
        id: changelogAfter
        uses: juliangruber/read-file-action@v1
        with:
          path: CHANGELOG.md

      - name: Echo changelog
        run: echo "${{ steps.changelogAfter.outputs.content }}"

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          changelog_file: CHANGELOG.md

      - name: Print release notes
        run: |
          echo "release notes: ${{ steps.extract-release-notes.outputs.release_notes }}"

      - name: Bump version in package.json
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add CHANGELOG.md package.json
          git commit --message "Prepare release ${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
          git tag -a ${{ github.event.inputs.version }} -m "Tagging a new version: ${{ github.event.inputs.version }}"
          git push && git push --tags

      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          name: "Release: ${{ github.event.inputs.version }}"
          draft: false
          prerelease: false
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Update Release Log
        uses: DamianReeves/write-file-action@master
        with:
          path: RELEASELOG.md
          contents: |
            ### ${{ steps.date.outputs.date }}: Version ${{ github.event.inputs.version }} deployed to ${{ github.event.inputs.environment }} by ${{ github.actor }}