Name: Custom Deploy

on :
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
        default: 'Testing'
      version:
        description: Version (eg: v1)
        required: true
env:
 node-version: 14.x
jobs:
  env_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "!startsWith(github.ref, 'refs/tags/')"

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: "${{ github.event.inputs.version}}"
          git-tag-version: 'true'