name: Main deploy

on:
  push:
    branches:
      - 'main'

env:
  node-version: 14.x

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "!startsWith(github.ref, 'refs/tags/')"

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Dependencies
        run: npm ci

      - name: Run Tests with coverage
        run: npm run test-ci

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
