name: Prepare Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (eg: 2023.1.1)'
        required: true
        type: string

concurrency:
  group: prepare-version
  cancel-in-progress: true

jobs:
  prepare_version:
    name: Build Version
    runs-on: ubuntu-latest

    steps:
      - name: Check version format
        run: |
          if [[ ${{ inputs.version }} =~ ^20[0-9][0-9]\.[0-9]\.[1-9][0-9]*$ ]]; 
          then
            exit 0
          else
            exit 1
          fi
      
