name: Tag Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (eg: 2023.1.1)'
        required: true
        type: string
  pull_request:
    types:
      - closed
    paths:
      - 'CHANGELOG.md'

concurrency:
  group: tag-version
  cancel-in-progress: true

jobs:    
  tag_version:
    name: Tag Version
    runs-on: ubuntu-latest
    env:
      VERSION: ''
    steps:
      - name: Get Version from pull request
        if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Version 20')
        shell: bash
        run: |
          echo "$(echo "${{ github.event.pull_request.title }}" | cut -c 9-20)" >> $VERSION
      - name: Get Version from Input
        if: github.event.inputs.version
        shell: bash
        run: |
          echo "${{ inputs.version }}" >> $VERSION
      - name: echo Version
        run: |
          echo "$VERSION"